variables:
  DOCKER_REPOSITORY: mendersoftware/mender-stress-test-client
  DOCKER_PUBLISH_COMMIT_TAG: ${CI_COMMIT_REF_SLUG:-master}
  # Setup containers to use docker dind service
  DOCKER_HOST: "tcp://docker:2376"
  DOCKER_CERT_PATH: "/certs/client"
  DOCKER_TLS_VERIFY: 1
  DOCKER_TLS_CERTDIR: "/certs" # Where docker:dind should generate certs
  GOLANG_VERSION: "1.25"

stages:
  - test
  - build
  - publish

include:
  - project: Northern.tech/Mender/mendertesting
    file:
      - qa-common/runner.yml
      - qa-common/retry.yml
  - project: 'Northern.tech/Mender/mendertesting'
    file: '.gitlab-ci-check-golang-lint.yml'
  - project: 'Northern.tech/Mender/mendertesting'
    file: '.gitlab-ci-check-commits-signoffs.yml'
  - project: 'Northern.tech/Mender/mendertesting'
    file: '.gitlab-ci-check-license.yml'
  - project: 'Northern.tech/Mender/mendertesting'
    file: '.gitlab-ci-github-status-updates.yml'
  - project: 'Northern.tech/Mender/mendertesting'
    file: '.gitlab-ci-check-docker-build.yml'

default:
  tags: !reference [.qa-common-default-runner, tags]
  retry: !reference [.qa-common-default-retry, retry]
